import { Injectable, Inject } from '@nestjs/common';
import { MailerService } from '@nestjs-modules/mailer';

 
@Injectable()
export class Emailservice {

  constructor(private mailService: MailerService) {}

  async plainTextEmail(email:string):Promise<any>{
    //let otp = Math.random();
    //console.log(otp)
    console.log("Generating Mail...");
    await this.mailService.sendMail({
     to: email,
     from: process.env.SENDER_EMAIL,
     subject: 'DEMO MAIL',
     text: 'this is a demo email generated by hardik nodemailer',
    })
    console.log("Email Sent");
    return "SUCCESSFUL";
  }
}
